# Generated by Django 3.0 on 2020-11-11 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programacao', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DesafiosPython',
        ),
    ]
