# Generated by Django 3.0 on 2020-11-11 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='desafiospython',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Título'),
        ),
    ]
