# Generated by Django 3.0 on 2020-11-02 14:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecss',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Texto'),
        ),
        migrations.AlterField(
            model_name='articledjango',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Texto'),
        ),
    ]
