# Generated by Django 3.0 on 2020-11-11 20:51

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesafiosPython',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Título')),
                ('desafio', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Desafio')),
                ('resposta', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Resposta')),
            ],
            options={
                'verbose_name_plural': 'Desafios Python',
                'db_table': 'tbDesafiosPython',
            },
        ),
    ]
