# Generated by Django 3.0 on 2020-11-12 14:44

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciciosBasicosPy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.DecimalField(decimal_places=0, default=0, max_digits=8)),
                ('exericio', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Exercício')),
                ('resposta', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Resposta')),
            ],
            options={
                'verbose_name_plural': 'Exericios Basicos PY',
                'db_table': 'ExerciciosBasicosPy',
            },
        ),
    ]
