# Generated by Django 3.0 on 2020-11-02 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programacao', '0002_auto_20201102_1115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlejavascrit',
            options={'verbose_name_plural': 'Articles JavaScripts'},
        ),
        migrations.AlterModelTable(
            name='articlejavascrit',
            table='tbArticleJavaScripts',
        ),
    ]
