# Generated by Django 3.0 on 2020-11-11 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programacao', '0002_auto_20201111_1729'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DesafiosPy',
        ),
    ]
