# Generated by Django 3.0 on 2020-11-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacao', '0003_auto_20201102_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleJavaScript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Título')),
                ('abstract', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subtítulo')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Texto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Articles JavaScript',
                'db_table': 'tbArticleJavaScript',
            },
        ),
    ]
