# Generated by Django 3.0 on 2020-11-03 21:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programacao', '0004_articlejavascript'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleheroku',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Texto'),
        ),
        migrations.AlterField(
            model_name='articlehtml',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Texto'),
        ),
        migrations.AlterField(
            model_name='articlejavascript',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Texto'),
        ),
        migrations.AlterField(
            model_name='articlejavascrit',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Texto'),
        ),
        migrations.AlterField(
            model_name='articlelibrary',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Texto'),
        ),
        migrations.AlterField(
            model_name='articlepython',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Texto'),
        ),
    ]
