# Generated by Django 3.0 on 2020-11-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacao', '0005_auto_20201103_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepython',
            name='capitulos',
            field=models.CharField(choices=[('default', 'default'), ('Estrutura de Dados', 'Estrutura de Dados'), ('Estrutura de Controle', 'Estrutura de Controle'), ('Exceções', 'Exceções'), ('Orientação a Objetos', 'Orientação a Objetos')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
