# Generated by Django 3.0 on 2020-11-11 17:10

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacao', '0005_auto_20201103_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesafiosPython',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desafioPython', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Desafio')),
                ('respostaPython', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Desafio')),
            ],
            options={
                'verbose_name_plural': 'Desafios Python',
                'db_table': 'tbDesafiosPython',
            },
        ),
        migrations.AddField(
            model_name='articlepython',
            name='capitulos',
            field=models.CharField(choices=[('default', 'default'), ('Estrutura de Dados', 'Estrutura de Dados'), ('Estrutura de Controle', 'Estrutura de Controle'), ('Exceções', 'Exceções'), ('Orientação a Objetos', 'Orientação a Objetos')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
