# Generated by Django 3.0 on 2020-11-11 17:03

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacao', '0006_articlepython_capitulos'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesafiosPython',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desafioPython', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Desafio')),
                ('respostaPython', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Desafio')),
            ],
        ),
    ]
