# Generated by Django 3.0 on 2020-11-11 17:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programacao', '0006_auto_20201111_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desafiospython',
            name='respostaPython',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Resposta'),
        ),
    ]
