# Generated by Django 3.0 on 2020-11-11 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programacao', '0007_auto_20201111_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepython',
            name='capitulos',
        ),
    ]
